.TH BEENODE-CLI "1" "June 2016" "beenode-cli 0.12"
.SH NAME
beenode-cli \- a remote procedure call client for Beenode Core. 
.SH SYNOPSIS
beenode-cli [options] <command> [params] \- Send command to Beenode Core. 
.TP
beenode-cli [options] help \- Asks Beenode Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the beenode-cli program. beenode-cli is an RPC client used to send commands to Beenode Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbeenoded\fP, \fBbeenode.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
